export const cardEmojis = [
  {
    emoji: "👇",
    emojiId: "1",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "👀",
    emojiId: "2",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "🙌",
    emojiId: "3",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "👋",
    emojiId: "4",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "🙏",
    emojiId: "5",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "🤔",
    emojiId: "6",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "🤦‍♂️",
    emojiId: "7",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "😔",
    emojiId: "8",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "👻",
    emojiId: "9",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "💀",
    emojiId: "10",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "👽",
    emojiId: "11",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "🎃",
    emojiId: "12",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "😻",
    emojiId: "13",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "🤑",
    emojiId: "14",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "🥳",
    emojiId: "15",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "😈",
    emojiId: "16",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "🤣",
    emojiId: "17",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "😱",
    emojiId: "18",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "👺",
    emojiId: "19",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "🥰",
    emojiId: "20",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "😕",
    emojiId: "21",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "😇",
    emojiId: "22",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "😁",
    emojiId: "23",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "👅",
    emojiId: "24",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "👃",
    emojiId: "25",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "🤏",
    emojiId: "26",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "👥",
    emojiId: "27",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "☂️",
    emojiId: "28",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "💍",
    emojiId: "29",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "🛀🏻",
    emojiId: "30",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "👩🏼‍🎓",
    emojiId: "31",
    matchFound: false,
    flipped: false,
  },
  {
    emoji: "💪🏽",
    emojiId: "32",
    matchFound: false,
    flipped: false,
  },
];